### ISSUE TITLE
compile in D10.4.2 Error

### ISSUE THREAD

**Issue by frankwu-delphi** [HashLoad/boss-ide#14]
[dcc32 Error] Boss.Commands.pas(29): E2010 Incompatible types: 'TNewLineEvent' and 'Procedure'.

i'm using Doscommand.pas from [https://github.com/TurboPack/DOSCommand](url)

**Comment by viniciussanchez** [comment]
The project has not yet been adapted for the new version of Delphi. Thanks for reporting

**Comment by TeoWin** [comment]
I can confirm that in the master branch downloaded 21-06-2022 the issue still is present, the Boss-IDE package cannot be installed in at least Delphi 11.1
